---
driver_plugin: vagrant
driver:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver:
    network:
      - [ 'private_network', { ip: '33.33.33.10' } ]
- name: ubuntu-13.10
  driver:
    network:
      - [ 'private_network', { ip: '33.33.33.11' } ]
- name: centos-6.4
  driver:
    network:
      - [ 'private_network', { ip: '33.33.33.12' } ]

suites:
- name: default
  run_list: ['recipe[go]']
