---
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: debian
    driver:
      name: vagrant
    driver_config:
      box:	'debian-7.8-bpk-chef-12.4.1'
      customize:
        server_name: 'kt-go'
        flavor: 'v.c1.m1536.d5.e0'
        server_create_timeout: 540
        server_active_timeout: 540

suites:
- name: default
  run_list:
  - recipe[gocd]
  attributes:
    java:
      jdk_version: 7
    gocd:
      server:
        max_mem: '1024m'
        min_mem: '512m'
      agent:
        autoregister:
          key: 'auto-register-key'
          environments: ['staging', 'perf']
          resources: ['foo', 'bar', 'baz']
          hostname: 'example-host'
