---
driver:
  name: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
- name: centos-6.4

suites:
- name: default
  run_list:
  - recipe[go]
  attributes: {}
